"""Generate Hong Kong JFIU STR XML for STREAMS 2 electronic filing.

The JFIU STREAMS 2 XML schema is provided to institutions under separate
cover.  This generator produces a structured XML document that mirrors
the JFIU STR Proforma form sections (Parts A-E) and can be adapted to
the exact STREAMS 2 schema once received.

Output is a *draft* — the MLRO / compliance officer MUST review and
validate all fields before submission to the JFIU.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Any, Optional
from xml.dom.minidom import parseString
from xml.etree.ElementTree import Element, SubElement, tostring

from .hk_str_models import (
    STRAdditionalInfo,
    STRGroundsForSuspicion,
    STRReportingInstitution,
    STRSubject,
    STRSuspiciousActivity,
    STRValidationResult,
    HKSubjectType,
)

DISCLAIMER = (
    "DRAFT — AI-ASSISTED OUTPUT. This XML was generated by the ANGELA AML platform "
    "using automated analysis. The MLRO / compliance officer MUST review every field "
    "and verify all data against source documents before submission to the JFIU via "
    "STREAMS 2. Do NOT file without human review."
)


def _sub(parent: Element, tag: str, text: Optional[str] = None, **attrs: str) -> Element:
    el = SubElement(parent, tag, **attrs)
    if text is not None:
        el.text = str(text)
    return el


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------

def validate_for_str_xml(
    reporting_institution: STRReportingInstitution,
    subject: STRSubject,
    suspicious_activity: STRSuspiciousActivity,
    grounds: STRGroundsForSuspicion,
    additional_info: STRAdditionalInfo,
) -> STRValidationResult:
    """Check whether the STR filing has enough data for XML generation."""
    errors: list[str] = []
    warnings: list[str] = []

    # Reporting institution
    if not reporting_institution.institution_name:
        errors.append("Reporting institution name is required.")
    if not reporting_institution.contact_name:
        warnings.append("Contact person name is recommended.")
    if not reporting_institution.contact_phone:
        warnings.append("Contact phone number is recommended.")

    # Subject
    if subject.subject_type == HKSubjectType.individual:
        if not subject.english_name and not subject.chinese_name:
            errors.append("Subject name (English or Chinese) is required for individual subjects.")
    else:
        if not subject.company_name:
            errors.append("Company name is required for corporate subjects.")
    if not subject.identity_documents:
        warnings.append("At least one identity document is recommended.")

    # Suspicious activity
    if not suspicious_activity.activity_period_begin:
        errors.append("Suspicious activity period begin date is required.")
    if not suspicious_activity.activity_period_end:
        errors.append("Suspicious activity period end date is required.")
    if suspicious_activity.total_amount_hkd is None and not suspicious_activity.transactions:
        warnings.append("Total amount or individual transaction details recommended.")

    # Grounds
    if not grounds.suspicious_indicators:
        errors.append("At least one suspicious indicator is required.")
    if not grounds.analysis_of_suspicion:
        errors.append("Analysis of suspicion is required.")

    # Narrative
    if not additional_info.narrative:
        warnings.append("Narrative (Part E) is empty — a detailed narrative strengthens the STR.")

    return STRValidationResult(
        ready=len(errors) == 0,
        errors=errors,
        warnings=warnings,
    )


# ---------------------------------------------------------------------------
# XML Generation
# ---------------------------------------------------------------------------

def generate_hk_str_xml(
    *,
    reporting_institution: dict[str, Any],
    subject: dict[str, Any],
    suspicious_activity: dict[str, Any],
    grounds_for_suspicion: dict[str, Any],
    additional_info: dict[str, Any],
    filing_id: str | None = None,
) -> str:
    """Build a JFIU STR XML document mirroring the proforma structure.

    Returns a pretty-printed XML string.
    """
    ri = STRReportingInstitution(**reporting_institution) if isinstance(reporting_institution, dict) else reporting_institution
    subj = STRSubject(**subject) if isinstance(subject, dict) else subject
    activity = STRSuspiciousActivity(**suspicious_activity) if isinstance(suspicious_activity, dict) else suspicious_activity
    grounds = STRGroundsForSuspicion(**grounds_for_suspicion) if isinstance(grounds_for_suspicion, dict) else grounds_for_suspicion
    addl = STRAdditionalInfo(**additional_info) if isinstance(additional_info, dict) else additional_info

    now_str = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    doc_id = filing_id or str(uuid.uuid4())

    root = Element("JFIU_STR")
    root.set("xmlns", "https://www.jfiu.gov.hk/str/v1")
    root.set("version", "1.0")
    root.set("generatedAt", now_str)
    root.set("filingId", doc_id)
    root.set("system", "ANGELA")

    # --- Part A: Reporting Institution ---
    part_a = _sub(root, "ReportingInstitution")
    if ri.institution_name:
        _sub(part_a, "InstitutionNameEnglish", ri.institution_name)
    if ri.institution_name_chinese:
        _sub(part_a, "InstitutionNameChinese", ri.institution_name_chinese)
    if ri.institution_type:
        _sub(part_a, "InstitutionTypeCode", ri.institution_type.value)
    if ri.regulator:
        _sub(part_a, "RegulatorCode", ri.regulator.value)
    if ri.license_number:
        _sub(part_a, "LicenseNumber", ri.license_number)
    if ri.address:
        _sub(part_a, "Address", ri.address)
    if ri.district:
        _sub(part_a, "District", ri.district)
    if ri.institution_reference:
        _sub(part_a, "InstitutionReference", ri.institution_reference)

    contact = _sub(part_a, "ContactPerson")
    if ri.contact_name:
        _sub(contact, "Name", ri.contact_name)
    if ri.contact_title:
        _sub(contact, "Title", ri.contact_title)
    if ri.contact_phone:
        _sub(contact, "Phone", ri.contact_phone)
    if ri.contact_email:
        _sub(contact, "Email", ri.contact_email)

    # --- Part B: Subject of Suspicion ---
    part_b = _sub(root, "SubjectOfSuspicion")
    _sub(part_b, "SubjectType", subj.subject_type.value)

    if subj.subject_type == HKSubjectType.individual:
        ind = _sub(part_b, "Individual")
        if subj.english_name:
            _sub(ind, "EnglishName", subj.english_name)
        if subj.chinese_name:
            _sub(ind, "ChineseName", subj.chinese_name)
        if subj.date_of_birth:
            _sub(ind, "DateOfBirth", subj.date_of_birth)
        if subj.nationality:
            _sub(ind, "Nationality", subj.nationality)
        if subj.occupation:
            _sub(ind, "Occupation", subj.occupation)
    else:
        corp = _sub(part_b, "Corporate")
        if subj.company_name:
            _sub(corp, "CompanyNameEnglish", subj.company_name)
        if subj.company_name_chinese:
            _sub(corp, "CompanyNameChinese", subj.company_name_chinese)
        if subj.business_registration_number:
            _sub(corp, "BusinessRegistrationNumber", subj.business_registration_number)
        if subj.nature_of_business:
            _sub(corp, "NatureOfBusiness", subj.nature_of_business)
        if subj.incorporation_place:
            _sub(corp, "PlaceOfIncorporation", subj.incorporation_place)

    if subj.address:
        _sub(part_b, "Address", subj.address)
    if subj.phone:
        _sub(part_b, "Phone", subj.phone)
    if subj.email:
        _sub(part_b, "Email", subj.email)

    for doc in subj.identity_documents:
        id_el = _sub(part_b, "IdentityDocument")
        if doc.id_type:
            _sub(id_el, "DocumentType", doc.id_type.value)
        if doc.id_number:
            _sub(id_el, "DocumentNumber", doc.id_number)
        if doc.issuing_country:
            _sub(id_el, "IssuingCountry", doc.issuing_country)

    for acct in subj.accounts:
        acct_el = _sub(part_b, "Account")
        _sub(acct_el, "AccountNumber", acct.account_number)
        if acct.account_type:
            _sub(acct_el, "AccountType", acct.account_type)
        if acct.account_opening_date:
            _sub(acct_el, "OpeningDate", acct.account_opening_date)
        if acct.account_status:
            _sub(acct_el, "Status", acct.account_status)

    if subj.relationship_to_institution:
        _sub(part_b, "RelationshipToInstitution", subj.relationship_to_institution)
    if subj.customer_since:
        _sub(part_b, "CustomerSince", subj.customer_since)

    # --- Part C: Suspicious Transaction Details ---
    part_c = _sub(root, "SuspiciousTransactionDetails")
    if activity.activity_period_begin:
        _sub(part_c, "ActivityPeriodBegin", activity.activity_period_begin)
    if activity.activity_period_end:
        _sub(part_c, "ActivityPeriodEnd", activity.activity_period_end)
    if activity.total_amount_hkd is not None:
        _sub(part_c, "TotalAmountHKD", f"{activity.total_amount_hkd:.2f}")
    if activity.total_amount_other_currency is not None and activity.other_currency:
        other_amt = _sub(part_c, "TotalAmountOtherCurrency", f"{activity.total_amount_other_currency:.2f}")
        other_amt.set("currency", activity.other_currency)

    for tx in activity.transactions:
        tx_el = _sub(part_c, "Transaction")
        if tx.transaction_date:
            _sub(tx_el, "Date", tx.transaction_date)
        if tx.transaction_type:
            _sub(tx_el, "TransactionType", tx.transaction_type.value)
        if tx.transaction_method:
            _sub(tx_el, "Method", tx.transaction_method.value)
        if tx.amount is not None:
            amt_el = _sub(tx_el, "Amount", f"{tx.amount:.2f}")
            amt_el.set("currency", tx.currency)
        if tx.counterparty_name:
            cp = _sub(tx_el, "Counterparty")
            _sub(cp, "Name", tx.counterparty_name)
            if tx.counterparty_account:
                _sub(cp, "Account", tx.counterparty_account)
            if tx.counterparty_institution:
                _sub(cp, "Institution", tx.counterparty_institution)
            if tx.counterparty_jurisdiction:
                _sub(cp, "Jurisdiction", tx.counterparty_jurisdiction)
        if tx.description:
            _sub(tx_el, "Description", tx.description)

    # --- Part D: Grounds for Suspicion ---
    part_d = _sub(root, "GroundsForSuspicion")
    for indicator_code in grounds.suspicious_indicators:
        _sub(part_d, "SuspiciousIndicator", code=indicator_code)
    if grounds.indicator_other_text:
        _sub(part_d, "IndicatorOtherText", grounds.indicator_other_text)
    if grounds.customer_explanation:
        _sub(part_d, "CustomerExplanation", grounds.customer_explanation)
    if grounds.analysis_of_suspicion:
        _sub(part_d, "AnalysisOfSuspicion", grounds.analysis_of_suspicion)
    _sub(part_d, "CustomerTippedOff", "Y" if grounds.customer_tipped_off else "N")
    _sub(part_d, "AccountFrozen", "Y" if grounds.account_frozen else "N")
    if grounds.account_frozen and grounds.account_frozen_date:
        _sub(part_d, "AccountFrozenDate", grounds.account_frozen_date)
    for ref in grounds.related_str_references:
        _sub(part_d, "RelatedSTRReference", ref)
    if grounds.suspected_offence:
        _sub(part_d, "SuspectedOffence", grounds.suspected_offence)

    # --- Part E: Additional Information ---
    part_e = _sub(root, "AdditionalInformation")
    if addl.narrative:
        full_narrative = f"{DISCLAIMER}\n\n---\n\n{addl.narrative}"
        _sub(part_e, "Narrative", full_narrative)
    if addl.supporting_documents_description:
        _sub(part_e, "SupportingDocumentsDescription", addl.supporting_documents_description)

    # Serialize
    raw_xml = tostring(root, encoding="unicode", xml_declaration=False)
    xml_declaration = '<?xml version="1.0" encoding="UTF-8"?>\n'

    try:
        pretty = parseString(raw_xml).toprettyxml(indent="  ", encoding=None)
        if isinstance(pretty, bytes):
            pretty = pretty.decode("utf-8")
        lines = pretty.split("\n")
        if lines and lines[0].startswith("<?xml"):
            lines = lines[1:]
        return xml_declaration + "\n".join(lines)
    except Exception:
        return xml_declaration + raw_xml
