"""Generate FinCEN BSA E-Filing SAR XML (Schema v1.6).

Produces XML conforming to the FinCEN SAR batch filing schema.  The output
is intended as a *draft* — the compliance officer MUST review and validate
the XML through their institution's BSA e-filing software before submission.

Party type codes used in this generator:
  35 - Transmitter (batch filer)
  37 - Transmitter Contact
  30 - Filing Institution
   8 - Contact for Filing Institution
  33 - Subject (individual)
  46 - Subject (entity — legal entity subject)
  34 - Financial Institution Where Activity Occurred
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Any, Optional
from xml.dom.minidom import parseString
from xml.etree.ElementTree import Element, SubElement, tostring

from .models import (
    SARFilingContact,
    SARFinancialInstitution,
    SARSubject,
    SARSuspiciousActivity,
    SARValidationResult,
    SubjectType,
)

FINCEN_NS = "www.fincen.gov/base"
XSI_NS = "http://www.w3.org/2001/XMLSchema-instance"

DISCLAIMER = (
    "DRAFT — AI-ASSISTED OUTPUT. This XML was generated by the ANGELA AML platform "
    "using automated analysis. A qualified compliance officer MUST review every field, "
    "verify all data against source documents, and validate through their institution's "
    "BSA e-filing software before submission to FinCEN. Do NOT file without human review."
)


class _SeqCounter:
    """Simple monotonic counter for XML SeqNum attributes."""

    def __init__(self, start: int = 1) -> None:
        self._n = start

    def next(self) -> str:
        val = self._n
        self._n += 1
        return str(val)


def _sub(parent: Element, tag: str, text: Optional[str] = None, **attrs: str) -> Element:
    """Create a sub-element, optionally setting text and attributes."""
    el = SubElement(parent, tag, **attrs)
    if text is not None:
        el.text = str(text)
    return el


def _add_address(parent: Element, seq: _SeqCounter, *, street: str | None,
                 city: str | None, state: str | None, zip_code: str | None,
                 country: str | None) -> None:
    """Append an <Address> block if any field is populated."""
    if not any([street, city, state, zip_code, country]):
        return
    addr = _sub(parent, "Address", SeqNum=seq.next())
    if city:
        _sub(addr, "RawCityText", city)
    if country:
        _sub(addr, "RawCountryCodeText", country)
    if state:
        _sub(addr, "RawStateCodeText", state)
    if street:
        _sub(addr, "RawStreetAddress1Text", street)
    if zip_code:
        _sub(addr, "RawZIPCode", zip_code)


def _add_phone(parent: Element, seq: _SeqCounter, *, number: str | None,
               extension: str | None = None) -> None:
    if not number:
        return
    phone = _sub(parent, "PhoneNumber", SeqNum=seq.next())
    _sub(phone, "PhoneNumberText", number)
    if extension:
        _sub(phone, "PhoneNumberExtensionText", extension)


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------

def validate_for_xml(
    subject: SARSubject,
    suspicious_activity: SARSuspiciousActivity,
    financial_institution: SARFinancialInstitution,
    filing_institution: SARFinancialInstitution,
    filing_contact: SARFilingContact,
    narrative: str | None,
) -> SARValidationResult:
    """Check whether the filing has enough data to generate valid XML."""
    errors: list[str] = []
    warnings: list[str] = []

    # Subject
    if subject.subject_type == SubjectType.individual:
        if not subject.last_name:
            errors.append("Subject last name is required for individual subjects.")
    else:
        if not subject.entity_name:
            errors.append("Entity name is required for entity subjects.")

    # Suspicious activity
    if not suspicious_activity.date_range_begin:
        errors.append("Suspicious activity begin date is required.")
    if not suspicious_activity.date_range_end:
        errors.append("Suspicious activity end date is required.")
    if (suspicious_activity.total_suspicious_amount is None
            and not suspicious_activity.no_amount_involved
            and not suspicious_activity.amount_unknown):
        errors.append("Total suspicious amount is required (or mark no_amount_involved / amount_unknown).")
    if not suspicious_activity.activity_type_codes:
        errors.append("At least one activity type code is required.")

    # Financial institution
    if not filing_institution.name:
        errors.append("Filing institution name is required.")
    if not filing_institution.tin:
        warnings.append("Filing institution TIN is recommended.")

    # Contact
    if not filing_contact.last_name:
        warnings.append("Filing contact last name is recommended.")

    # Narrative
    if not narrative:
        warnings.append("SAR narrative (Part V) is empty.")

    # Non-critical suggestions
    if not subject.address_street:
        warnings.append("Subject address is recommended if available.")
    if not subject.ssn_itin and not subject.ein:
        warnings.append("Subject TIN/SSN is recommended if known.")
    if not financial_institution.name:
        warnings.append("Institution where activity occurred is recommended if different from filing institution.")

    return SARValidationResult(
        ready=len(errors) == 0,
        errors=errors,
        warnings=warnings,
    )


# ---------------------------------------------------------------------------
# XML Generation
# ---------------------------------------------------------------------------

def generate_fincen_xml(
    *,
    filing_type: str = "initial",
    prior_report_bsa_id: str | None = None,
    subject: dict[str, Any],
    suspicious_activity: dict[str, Any],
    financial_institution: dict[str, Any],
    filing_institution: dict[str, Any],
    filing_contact: dict[str, Any],
    narrative: str | None,
    filing_id: str | None = None,
) -> str:
    """Build a complete FinCEN SAR XML v1.6 document.

    Returns a pretty-printed XML string.  The caller MUST validate through
    their institution's BSA e-filing software before submitting.
    """
    subj = SARSubject(**subject) if isinstance(subject, dict) else subject
    activity = SARSuspiciousActivity(**suspicious_activity) if isinstance(suspicious_activity, dict) else suspicious_activity
    fi_where = SARFinancialInstitution(**financial_institution) if isinstance(financial_institution, dict) else financial_institution
    fi_filing = SARFinancialInstitution(**filing_institution) if isinstance(filing_institution, dict) else filing_institution
    contact = SARFilingContact(**filing_contact) if isinstance(filing_contact, dict) else filing_contact

    seq = _SeqCounter(1)
    now_str = datetime.now(timezone.utc).strftime("%Y%m%d")
    doc_id = filing_id or str(uuid.uuid4())

    # Root
    root = Element("EFilingBatchXML")
    root.set("xmlns", FINCEN_NS)
    root.set("xmlns:xsi", XSI_NS)
    root.set("xsi:schemaLocation", f"{FINCEN_NS} FinCEN_SARBatch_v1.6.xsd")
    root.set("FormTypeCode", "SARX")
    root.set("ActivityCount", "1")
    root.set("TotalAmount", str(int(activity.total_suspicious_amount or 0)))
    root.set("PartyCount", "0")  # updated at end
    root.set("SeqNum", seq.next())

    party_count = 0

    # -- Activity --
    act_el = _sub(root, "Activity", SeqNum=seq.next())
    if prior_report_bsa_id:
        _sub(act_el, "EFilingPriorDocumentNumber", prior_report_bsa_id)
    _sub(act_el, "FilingDateText", contact.date_filed or now_str)

    # ActivityAssociation
    assoc = _sub(act_el, "ActivityAssociation", SeqNum=seq.next())
    is_initial = filing_type == "initial"
    _sub(assoc, "CorrectsAmendsPriorReportIndicator", "N" if is_initial else "Y")
    _sub(assoc, "InitialReportIndicator", "Y" if is_initial else "N")
    if filing_type == "joint":
        _sub(assoc, "JointReportIndicator", "Y")

    # -- Filing Institution (Party 30) --
    fi_party = _sub(act_el, "Party", SeqNum=seq.next())
    party_count += 1
    _sub(fi_party, "ActivityPartyTypeCode", "30")
    if fi_filing.tin:
        pid = _sub(fi_party, "PartyIdentification", SeqNum=seq.next())
        _sub(pid, "PartyIdentificationNumberText", fi_filing.tin)
        _sub(pid, "PartyIdentificationTypeCode", fi_filing.tin_type.value if fi_filing.tin_type else "2")
    if fi_filing.name:
        pn = _sub(fi_party, "PartyName", SeqNum=seq.next())
        _sub(pn, "PartyNameTypeCode", "L")
        _sub(pn, "RawPartyFullName", fi_filing.name)
    _add_address(fi_party, seq,
                 street=fi_filing.address_street, city=fi_filing.address_city,
                 state=fi_filing.address_state, zip_code=fi_filing.address_zip,
                 country=fi_filing.address_country)
    if fi_filing.institution_type:
        oc = _sub(fi_party, "OrganizationClassificationTypeSubtype", SeqNum=seq.next())
        _sub(oc, "OrganizationSubtypeID", fi_filing.institution_type.value)
    if fi_filing.primary_federal_regulator:
        _sub(fi_party, "PrimaryRegulatorTypeCode", fi_filing.primary_federal_regulator.value)
    if fi_filing.id_number:
        _sub(fi_party, "PartyIdentificationIDNumber", fi_filing.id_number)

    # -- Contact for Filing Institution (Party 8) --
    ct_party = _sub(act_el, "Party", SeqNum=seq.next())
    party_count += 1
    _sub(ct_party, "ActivityPartyTypeCode", "8")
    if contact.last_name or contact.first_name:
        cn = _sub(ct_party, "PartyName", SeqNum=seq.next())
        _sub(cn, "PartyNameTypeCode", "L")
        if contact.last_name:
            _sub(cn, "RawEntityIndividualLastName", contact.last_name)
        if contact.first_name:
            _sub(cn, "RawIndividualFirstName", contact.first_name)
        if contact.middle_name:
            _sub(cn, "RawIndividualMiddleName", contact.middle_name)
    if contact.title:
        _sub(ct_party, "RawIndividualTitleText", contact.title)
    _add_phone(ct_party, seq, number=contact.phone_number, extension=contact.phone_extension)

    # -- Subject (Party 33 or 46) --
    subj_party = _sub(act_el, "Party", SeqNum=seq.next())
    party_count += 1
    subj_code = "33" if subj.subject_type == SubjectType.individual else "46"
    _sub(subj_party, "ActivityPartyTypeCode", subj_code)

    if subj.date_of_birth:
        _sub(subj_party, "IndividualBirthDateText", subj.date_of_birth)

    # Subject name
    sn = _sub(subj_party, "PartyName", SeqNum=seq.next())
    _sub(sn, "PartyNameTypeCode", "L")
    if subj.subject_type == SubjectType.individual:
        if subj.last_name:
            _sub(sn, "RawEntityIndividualLastName", subj.last_name)
        if subj.first_name:
            _sub(sn, "RawIndividualFirstName", subj.first_name)
        if subj.middle_name:
            _sub(sn, "RawIndividualMiddleName", subj.middle_name)
        if subj.suffix:
            _sub(sn, "RawIndividualNameSuffixText", subj.suffix)
    else:
        if subj.entity_name:
            _sub(sn, "RawPartyFullName", subj.entity_name)

    # DBA / AKA name
    if subj.dba_name:
        sn_dba = _sub(subj_party, "PartyName", SeqNum=seq.next())
        _sub(sn_dba, "PartyNameTypeCode", "DBA")
        _sub(sn_dba, "RawPartyFullName", subj.dba_name)

    # Subject address
    _add_address(subj_party, seq,
                 street=subj.address_street, city=subj.address_city,
                 state=subj.address_state, zip_code=subj.address_zip,
                 country=subj.address_country)

    # Subject phone
    _add_phone(subj_party, seq, number=subj.phone_number, extension=subj.phone_extension)

    # Subject TIN
    if subj.ssn_itin:
        sp_id = _sub(subj_party, "PartyIdentification", SeqNum=seq.next())
        _sub(sp_id, "PartyIdentificationNumberText", subj.ssn_itin)
        _sub(sp_id, "PartyIdentificationTypeCode", "1")  # SSN/ITIN
    elif subj.ein:
        sp_id = _sub(subj_party, "PartyIdentification", SeqNum=seq.next())
        _sub(sp_id, "PartyIdentificationNumberText", subj.ein)
        _sub(sp_id, "PartyIdentificationTypeCode", "2")  # EIN

    # Government IDs
    for gid in subj.government_ids:
        if gid.id_number:
            gid_el = _sub(subj_party, "PartyIdentification", SeqNum=seq.next())
            _sub(gid_el, "PartyIdentificationNumberText", gid.id_number)
            if gid.id_type:
                _sub(gid_el, "PartyIdentificationTypeCode", gid.id_type.value)
            if gid.issuing_state:
                _sub(gid_el, "OtherIssuerStateText", gid.issuing_state)
            if gid.issuing_country:
                _sub(gid_el, "OtherIssuerCountryText", gid.issuing_country)

    # Occupation
    if subj.occupation_or_business:
        _sub(subj_party, "PartyOccupationBusinessText", subj.occupation_or_business)
    if subj.naics_code:
        _sub(subj_party, "NAICSCode", subj.naics_code)

    # Accounts
    for acct in subj.accounts:
        acct_el = _sub(subj_party, "Account", SeqNum=seq.next())
        _sub(acct_el, "AccountNumberText", acct.account_number)
        pa = _sub(acct_el, "PartyAccountAssociation", SeqNum=seq.next())
        if acct.account_type:
            _sub(pa, "PartyAccountAssociationTypeCode", acct.account_type.value)
        if acct.still_open is not None:
            _sub(pa, "AccountClosedIndicator", "N" if acct.still_open else "Y")

    # Subject email
    if subj.email:
        _sub(subj_party, "ElectronicAddressText", subj.email)

    # -- Financial Institution Where Activity Occurred (Party 34) --
    if fi_where.name:
        fi_where_party = _sub(act_el, "Party", SeqNum=seq.next())
        party_count += 1
        _sub(fi_where_party, "ActivityPartyTypeCode", "34")
        if fi_where.tin:
            fwp_id = _sub(fi_where_party, "PartyIdentification", SeqNum=seq.next())
            _sub(fwp_id, "PartyIdentificationNumberText", fi_where.tin)
            _sub(fwp_id, "PartyIdentificationTypeCode",
                 fi_where.tin_type.value if fi_where.tin_type else "2")
        fwn = _sub(fi_where_party, "PartyName", SeqNum=seq.next())
        _sub(fwn, "PartyNameTypeCode", "L")
        _sub(fwn, "RawPartyFullName", fi_where.name)
        _add_address(fi_where_party, seq,
                     street=fi_where.address_street, city=fi_where.address_city,
                     state=fi_where.address_state, zip_code=fi_where.address_zip,
                     country=fi_where.address_country)
        if fi_where.institution_type:
            oc2 = _sub(fi_where_party, "OrganizationClassificationTypeSubtype", SeqNum=seq.next())
            _sub(oc2, "OrganizationSubtypeID", fi_where.institution_type.value)
        if fi_where.primary_federal_regulator:
            _sub(fi_where_party, "PrimaryRegulatorTypeCode",
                 fi_where.primary_federal_regulator.value)

        # Branch info
        if fi_where.branch_address_street or fi_where.branch_address_city:
            _add_address(fi_where_party, seq,
                         street=fi_where.branch_address_street,
                         city=fi_where.branch_address_city,
                         state=fi_where.branch_address_state,
                         zip_code=fi_where.branch_address_zip,
                         country=fi_where.address_country)

    # -- Suspicious Activity --
    sa_el = _sub(act_el, "SuspiciousActivity", SeqNum=seq.next())

    for code in activity.activity_type_codes:
        sa_class = _sub(sa_el, "SuspiciousActivityClassification", SeqNum=seq.next())
        _sub(sa_class, "SuspiciousActivitySubtypeID", code)
    if activity.activity_type_other_text:
        _sub(sa_el, "SuspiciousActivityOtherText", activity.activity_type_other_text)

    sa_dr = _sub(sa_el, "SuspiciousActivityDateRange", SeqNum=seq.next())
    if activity.date_range_begin:
        _sub(sa_dr, "DateRangeBeginDateText", activity.date_range_begin)
    if activity.date_range_end:
        _sub(sa_dr, "DateRangeEndDateText", activity.date_range_end)

    if activity.total_suspicious_amount is not None:
        _sub(sa_el, "TotalSuspiciousAmountText", str(int(activity.total_suspicious_amount)))
    if activity.no_amount_involved:
        _sub(sa_el, "AmountUnknownIndicator", "Y")
    if activity.cumulative_amount is not None:
        _sub(sa_el, "CumulativeAmountText", str(int(activity.cumulative_amount)))

    # Payment instruments
    for inst in activity.instrument_types:
        _sub(sa_el, "SuspiciousActivityPaymentInstrumentTypeCode", inst)
    if activity.instrument_other_text:
        _sub(sa_el, "SuspiciousActivityPaymentInstrumentOtherText", activity.instrument_other_text)

    # Product/service
    for prod in activity.product_types:
        _sub(sa_el, "SuspiciousActivityProductServiceTypeCode", prod)
    if activity.product_other_text:
        _sub(sa_el, "SuspiciousActivityProductServiceOtherText", activity.product_other_text)

    # Law enforcement
    if activity.law_enforcement_contacted:
        _sub(sa_el, "LawEnforcementContactedIndicator", "Y")
        if activity.law_enforcement_name:
            _sub(sa_el, "LawEnforcementContactedName", activity.law_enforcement_name)

    # IP addresses (cyber-related SARs)
    for ip in activity.ip_addresses:
        _sub(sa_el, "IPAddressText", ip)

    # -- Narrative (Part V) --
    if narrative:
        full_narrative = f"{DISCLAIMER}\n\n---\n\n{narrative}"
        _sub(act_el, "EFilingActivityDescription", full_narrative)

    # Update party count
    root.set("PartyCount", str(party_count))

    raw_xml = tostring(root, encoding="unicode", xml_declaration=False)
    xml_declaration = '<?xml version="1.0" encoding="UTF-8"?>\n'

    try:
        pretty = parseString(raw_xml).toprettyxml(indent="  ", encoding=None)
        if isinstance(pretty, bytes):
            pretty = pretty.decode("utf-8")
        # minidom adds its own xml declaration, strip and use ours
        lines = pretty.split("\n")
        if lines and lines[0].startswith("<?xml"):
            lines = lines[1:]
        return xml_declaration + "\n".join(lines)
    except Exception:
        return xml_declaration + raw_xml
