import { generateSAR, type SARResponse } from "../api/client";
import { ENTITY_LINK_EVENT, markdownToSafeHtml, renderMarkdownInto } from "./markdown";

// ── DOM setup ──────────────────────────────────────────────────────────

const panel = document.getElementById("sar-panel") as HTMLDivElement;
const closeBtn = document.getElementById("sar-close") as HTMLButtonElement;
const contentEl = document.getElementById("sar-content") as HTMLDivElement;

let currentData: SARResponse | null = null;

closeBtn.addEventListener("click", hide);

// ── Public API ─────────────────────────────────────────────────────────

export function hide(): void {
  panel.classList.remove("open");
}

export async function generate(entityId: string, bucket: number): Promise<void> {
  panel.classList.add("open");
  contentEl.innerHTML = `
    <div class="sar-loading">
      <div class="sar-spinner"></div>
      <div class="sar-loading-text">Generating SAR narrative...</div>
    </div>
  `;

  try {
    const data = await generateSAR(entityId, bucket);
    currentData = data;
    renderNarrative(data);
  } catch (err) {
    contentEl.innerHTML = `
      <div class="sar-error">
        Failed to generate SAR: ${err instanceof Error ? err.message : "Unknown error"}
      </div>
    `;
  }
}

// ── Render ──────────────────────────────────────────────────────────────

function renderNarrative(data: SARResponse): void {
  const payload = data.payload as Record<string, unknown>;
  const riskPct = ((payload.risk_score as number) * 100).toFixed(0);

  contentEl.innerHTML = `
    <div class="sar-header-info">
      <div class="sar-meta">
        <span class="sar-label">Subject</span>
        <button id="sar-subject-link" class="sar-entity-link">${data.entity_id}</button>
      </div>
      <div class="sar-meta">
        <span class="sar-label">Risk Score</span>
        <span class="sar-value sar-risk">${riskPct}%</span>
      </div>
      <div class="sar-meta">
        <span class="sar-label">Time Window</span>
        <span class="sar-value">Window ${data.bucket + 1}</span>
      </div>
    </div>
    <div class="sar-hint">Tip: click any entity ID in this report to open it in the graph.</div>
    <div id="sar-narrative-md" class="sar-narrative markdown-content"></div>
    <div class="sar-actions">
      <button id="sar-focus-btn" class="sar-btn">Open Subject in Graph</button>
      <button id="sar-export-btn" class="sar-btn">Export PDF</button>
      <button id="sar-copy-btn" class="sar-btn sar-btn-secondary">Copy Text</button>
    </div>
  `;
  const narrativeEl = document.getElementById("sar-narrative-md");
  if (narrativeEl) {
    renderMarkdownInto(narrativeEl, data.narrative);
  }

  document.getElementById("sar-subject-link")!.addEventListener("click", () => focusEntity(data.entity_id));
  document.getElementById("sar-focus-btn")!.addEventListener("click", () => focusEntity(data.entity_id));
  document.getElementById("sar-export-btn")!.addEventListener("click", exportPDF);
  document.getElementById("sar-copy-btn")!.addEventListener("click", copyText);
}

// ── PDF export via print window ─────────────────────────────────────────

function exportPDF(): void {
  if (!currentData) return;
  const payload = currentData.payload as Record<string, unknown>;
  const riskPct = ((payload.risk_score as number) * 100).toFixed(0);
  const narrativeHtml = markdownToSafeHtml(currentData.narrative);

  const html = `<!DOCTYPE html>
<html><head>
<title>SAR Report — ${currentData.entity_id}</title>
<style>
  body { font-family: 'Times New Roman', serif; margin: 40px 60px; color: #111; line-height: 1.6; }
  h1 { font-size: 18px; text-align: center; margin-bottom: 4px; }
  .subtitle { text-align: center; font-size: 12px; color: #666; margin-bottom: 24px; }
  .meta-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 13px; }
  .meta-table td { padding: 4px 8px; border: 1px solid #ddd; }
  .meta-table td:first-child { font-weight: bold; width: 140px; background: #f8f8f8; }
  .narrative { font-size: 13px; line-height: 1.7; }
  .narrative p { margin: 0 0 10px; }
  .narrative h1, .narrative h2, .narrative h3 { margin: 14px 0 8px; }
  .narrative ul, .narrative ol { margin: 0 0 10px 20px; }
  .narrative code { font-family: monospace; background: #f2f2f2; padding: 1px 4px; border-radius: 3px; }
  .footer { margin-top: 30px; font-size: 10px; color: #999; text-align: center; border-top: 1px solid #ddd; padding-top: 8px; }
</style>
</head><body>
<h1>Suspicious Activity Report</h1>
<div class="subtitle">Generated by ANGELA — Anomaly Network Graph for Explainable Laundering Analysis</div>
<table class="meta-table">
  <tr><td>Subject ID</td><td>${escapeHtml(currentData.entity_id)}</td></tr>
  <tr><td>Entity Type</td><td>${escapeHtml(String(payload.entity_type || "account"))}</td></tr>
  <tr><td>Institution</td><td>${escapeHtml(String(payload.bank || "N/A"))}</td></tr>
  <tr><td>Risk Score</td><td>${riskPct}%</td></tr>
  <tr><td>Time Window</td><td>Window ${currentData.bucket + 1}</td></tr>
  <tr><td>Report Date</td><td>${new Date().toISOString().slice(0, 10)}</td></tr>
</table>
<div class="narrative">${narrativeHtml}</div>
<div class="footer">This report was auto-generated by ANGELA for investigative purposes. All findings require human review.</div>
</body></html>`;

  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(html);
  win.document.close();
  // Trigger print dialog (which allows Save as PDF)
  setTimeout(() => win.print(), 300);
}

// ── Copy to clipboard ───────────────────────────────────────────────────

function copyText(): void {
  if (!currentData) return;
  navigator.clipboard.writeText(currentData.narrative).then(() => {
    const btn = document.getElementById("sar-copy-btn");
    if (btn) {
      btn.textContent = "Copied!";
      setTimeout(() => { btn.textContent = "Copy Text"; }, 1500);
    }
  });
}

// ── Util ────────────────────────────────────────────────────────────────

function escapeHtml(text: string): string {
  const div = document.createElement("div");
  div.textContent = text;
  return div.innerHTML;
}

function focusEntity(entityId: string): void {
  window.dispatchEvent(new CustomEvent(ENTITY_LINK_EVENT, { detail: { entityId } }));
  hide();
}
